
CPPFLAGS = /I.. $(CPPFLAGS)

ALL_TESTS = base_pushpop.exe base_multi_pushpop.exe base_destruct.exe base_exceptions.exe base_construct.exe

all: $(ALL_TESTS)

check: $(ALL_TESTS)
	set ALL_TESTS=$(ALL_TESTS)
	call <<run_tests.bat
@echo off
setlocal enabledelayedexpansion
for %%t in (%ALL_TESTS%) do %%t
<<

clean:
	del /q *.obj
	del /q $(ALL_TESTS)
